# Generated by Django 3.2.4 on 2021-06-15 13:22

from django.db import migrations, models


from Data import Data
import time
import pandas as pd


def init_data(apps, schema_editor):
    now = pd.Timestamp(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())))
    start_year = now.year - 10
    start = pd.Timestamp(start_year, 1, 1)
    data = Data(str(start), str(now), 2.5)

    filename = 'data.csv'
    data.download(filename)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mag', models.FloatField()),
            ],
        ),
    ]
